loaded animation
bckrm/hubble-technology pull request #50
Opened 2021-03-23 22:53 UTC by kcbreuil

2021-03-24 13:30 UTC, asasmith commented
Need to address the positioning of this `:after` element.

![Screen Shot 2021-03-24 at 9 29 07 AM](https://user-images.githubusercontent.com/11489171/112318466-70712600-8c83-11eb-9454-11c1d02b7cf3.png)
![Screen Shot 2021-03-24 at 9 29 18 AM](https://user-images.githubusercontent.com/11489171/112318467-7109bc80-8c83-11eb-813b-f051a01487a5.png)

2021-03-24 13:37 UTC, asasmith requested changes
Check the mobile styles for the text content (`Get a complete picture of your data`). I think the font-size is smaller on small sceens.

2021-03-24 13:37 UTC, asasmith commented on web/src/components/index/indexIntro.js
> +// import Img from 'gatsby-image';
Remove completely.

2021-03-24 13:37 UTC, asasmith commented on web/src/components/index/indexIntro.js
> +    const [finishedAnimation, setFinishedAnimation] = useState(false);
Small thing, can we change this to `isFinishedAnimation` or `isAnimationFinished`? I think the `is` helps to communicate what this prop is for.

2021-03-24 16:29 UTC, kcbreuil commented
> Need to address the positioning of this `:after` element.
> 
> ![Screen Shot 2021-03-24 at 9 29 07 AM](https://user-images.githubusercontent.com/11489171/112318466-70712600-8c83-11eb-9454-11c1d02b7cf3.png)
> ![Screen Shot 2021-03-24 at 9 29 18 AM](https://user-images.githubusercontent.com/11489171/112318467-7109bc80-8c83-11eb-813b-f051a01487a5.png)

Yeah I am curious if we can use a graphic instead? I was trying to fix it last night but didnt have much luck since the container its contingent on changes throughout the animation.

2021-03-24 16:38 UTC, asasmith commented
> > Need to address the positioning of this `:after` element.
> > ![Screen Shot 2021-03-24 at 9 29 07 AM](https://user-images.githubusercontent.com/11489171/112318466-70712600-8c83-11eb-9454-11c1d02b7cf3.png)
> > ![Screen Shot 2021-03-24 at 9 29 18 AM](https://user-images.githubusercontent.com/11489171/112318467-7109bc80-8c83-11eb-813b-f051a01487a5.png)
> 
> Yeah I am curious if we can use a graphic instead? I was trying to fix it last night but didnt have much luck since the container its contingent on changes throughout the animation.

sounds like we need to change the container then.

2021-03-24 17:16 UTC, kcbreuil commented
> > > Need to address the positioning of this `:after` element.
> > > ![Screen Shot 2021-03-24 at 9 29 07 AM](https://user-images.githubusercontent.com/11489171/112318466-70712600-8c83-11eb-9454-11c1d02b7cf3.png)
> > > ![Screen Shot 2021-03-24 at 9 29 18 AM](https://user-images.githubusercontent.com/11489171/112318467-7109bc80-8c83-11eb-813b-f051a01487a5.png)
> > 
> > 
> > Yeah I am curious if we can use a graphic instead? I was trying to fix it last night but didnt have much luck since the container its contingent on changes throughout the animation.
> 
> sounds like we need to change the container then.
> 
> yeah, if you move the `:after` element to the `h2` instead of the ~body paragraph~ wrapping div it should work. Need to add `relative` to the `h2` as well.
> 
> Let me know if you have any questions

@asasmith I tried that last night and it still moves up and then down again. I think we need to put it on the `P` element actually, since the wireframes shows that it "reappears" with the text

2021-03-24 17:25 UTC, asasmith commented
> > > > Need to address the positioning of this `:after` element.
> > > > ![Screen Shot 2021-03-24 at 9 29 07 AM](https://user-images.githubusercontent.com/11489171/112318466-70712600-8c83-11eb-9454-11c1d02b7cf3.png)
> > > > ![Screen Shot 2021-03-24 at 9 29 18 AM](https://user-images.githubusercontent.com/11489171/112318467-7109bc80-8c83-11eb-813b-f051a01487a5.png)
> > > 
> > > 
> > > Yeah I am curious if we can use a graphic instead? I was trying to fix it last night but didnt have much luck since the container its contingent on changes throughout the animation.
> > 
> > 
> > sounds like we need to change the container then.
> > yeah, if you move the `:after` element to the `h2` instead of the ~body paragraph~ wrapping div it should work. Need to add `relative` to the `h2` as well.
> > Let me know if you have any questions
> 
> @asasmith I tried that last night and it still moves up and then down again. I think we need to put it on the `P` element actually, since the wireframes shows that it "reappears" with the text
> 
> [
> <img alt="Screen Shot 2021-03-24 at 1 15 52 PM" width="489" src="https://user-images.githubusercontent.com/61708936/112355255-db325980-8ca3-11eb-8d51-4eedf6bc04b1.png">
> <img alt="Screen Shot 2021-03-24 at 1 15 20 PM" width="466" src="https://user-images.githubusercontent.com/61708936/112355302-e5ecee80-8ca3-11eb-9e49-78a6cc46af2d.png">
> 
> ](url)

My guess is the correct parent element didn't have `position: relative`.

2021-03-24 17:30 UTC, kcbreuil commented
> > > > > Need to address the positioning of this `:after` element.
> > > > > ![Screen Shot 2021-03-24 at 9 29 07 AM](https://user-images.githubusercontent.com/11489171/112318466-70712600-8c83-11eb-9454-11c1d02b7cf3.png)
> > > > > ![Screen Shot 2021-03-24 at 9 29 18 AM](https://user-images.githubusercontent.com/11489171/112318467-7109bc80-8c83-11eb-813b-f051a01487a5.png)
> > > > 
> > > > 
> > > > Yeah I am curious if we can use a graphic instead? I was trying to fix it last night but didnt have much luck since the container its contingent on changes throughout the animation.
> > > 
> > > 
> > > sounds like we need to change the container then.
> > > yeah, if you move the `:after` element to the `h2` instead of the ~body paragraph~ wrapping div it should work. Need to add `relative` to the `h2` as well.
> > > Let me know if you have any questions
> > 
> > 
> > @asasmith I tried that last night and it still moves up and then down again. I think we need to put it on the `P` element actually, since the wireframes shows that it "reappears" with the text
> > [
> > <img alt="Screen Shot 2021-03-24 at 1 15 52 PM" width="489" src="https://user-images.githubusercontent.com/61708936/112355255-db325980-8ca3-11eb-8d51-4eedf6bc04b1.png">
> > <img alt="Screen Shot 2021-03-24 at 1 15 20 PM" width="466" src="https://user-images.githubusercontent.com/61708936/112355302-e5ecee80-8ca3-11eb-9e49-78a6cc46af2d.png">
> > ](url)
> 
> My guess is the correct parent element didn't have `position: relative`.

it did. i double checked and anytime i put relative the entire thing disappears. I have a fix, pushing up now

2021-03-25 14:09 UTC, asasmith approved these changes

2021-03-25 14:10 UTC, merged